/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.mdapi;

public class CThostFtdcExchangeExecOrderField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcExchangeExecOrderField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcExchangeExecOrderField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcExchangeExecOrderField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniMdApiJNI.delete_CThostFtdcExchangeExecOrderField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVolume(int value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_Volume_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_RequestID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_BusinessUnit_get(swigCPtr, this);
  }

  public void setOffsetFlag(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_OffsetFlag_set(swigCPtr, this, value);
  }

  public char getOffsetFlag() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_OffsetFlag_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_HedgeFlag_get(swigCPtr, this);
  }

  public void setActionType(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ActionType_set(swigCPtr, this, value);
  }

  public char getActionType() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ActionType_get(swigCPtr, this);
  }

  public void setPosiDirection(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_PosiDirection_set(swigCPtr, this, value);
  }

  public char getPosiDirection() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_PosiDirection_get(swigCPtr, this);
  }

  public void setReservePositionFlag(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ReservePositionFlag_set(swigCPtr, this, value);
  }

  public char getReservePositionFlag() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ReservePositionFlag_get(swigCPtr, this);
  }

  public void setCloseFlag(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_CloseFlag_set(swigCPtr, this, value);
  }

  public char getCloseFlag() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_CloseFlag_get(swigCPtr, this);
  }

  public void setExecOrderLocalID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExecOrderLocalID_set(swigCPtr, this, value);
  }

  public String getExecOrderLocalID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExecOrderLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_InstallID_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_NotifySequence_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_SettlementID_get(swigCPtr, this);
  }

  public void setExecOrderSysID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExecOrderSysID_set(swigCPtr, this, value);
  }

  public String getExecOrderSysID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExecOrderSysID_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_InsertTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_CancelTime_get(swigCPtr, this);
  }

  public void setExecResult(char value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExecResult_set(swigCPtr, this, value);
  }

  public char getExecResult() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ExecResult_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_SequenceNo_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_BranchID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return CTPMiniMdApiJNI.CThostFtdcExchangeExecOrderField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcExchangeExecOrderField() {
    this(CTPMiniMdApiJNI.new_CThostFtdcExchangeExecOrderField(), true);
  }

}
