/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.mdapi;

public class CThostFtdcDiscountField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcDiscountField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcDiscountField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcDiscountField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniMdApiJNI.delete_CThostFtdcDiscountField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniMdApiJNI.CThostFtdcDiscountField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniMdApiJNI.CThostFtdcDiscountField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorRange(char value) {
    CTPMiniMdApiJNI.CThostFtdcDiscountField_InvestorRange_set(swigCPtr, this, value);
  }

  public char getInvestorRange() {
    return CTPMiniMdApiJNI.CThostFtdcDiscountField_InvestorRange_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniMdApiJNI.CThostFtdcDiscountField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniMdApiJNI.CThostFtdcDiscountField_InvestorID_get(swigCPtr, this);
  }

  public void setDiscount(double value) {
    CTPMiniMdApiJNI.CThostFtdcDiscountField_Discount_set(swigCPtr, this, value);
  }

  public double getDiscount() {
    return CTPMiniMdApiJNI.CThostFtdcDiscountField_Discount_get(swigCPtr, this);
  }

  public CThostFtdcDiscountField() {
    this(CTPMiniMdApiJNI.new_CThostFtdcDiscountField(), true);
  }

}
