/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.mdapi;

public class CThostFtdcQryBulletinField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQryBulletinField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQryBulletinField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcQryBulletinField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniMdApiJNI.delete_CThostFtdcQryBulletinField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    CTPMiniMdApiJNI.CThostFtdcQryBulletinField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniMdApiJNI.CThostFtdcQryBulletinField_ExchangeID_get(swigCPtr, this);
  }

  public void setBulletinID(int value) {
    CTPMiniMdApiJNI.CThostFtdcQryBulletinField_BulletinID_set(swigCPtr, this, value);
  }

  public int getBulletinID() {
    return CTPMiniMdApiJNI.CThostFtdcQryBulletinField_BulletinID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    CTPMiniMdApiJNI.CThostFtdcQryBulletinField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return CTPMiniMdApiJNI.CThostFtdcQryBulletinField_SequenceNo_get(swigCPtr, this);
  }

  public void setNewsType(String value) {
    CTPMiniMdApiJNI.CThostFtdcQryBulletinField_NewsType_set(swigCPtr, this, value);
  }

  public String getNewsType() {
    return CTPMiniMdApiJNI.CThostFtdcQryBulletinField_NewsType_get(swigCPtr, this);
  }

  public void setNewsUrgency(char value) {
    CTPMiniMdApiJNI.CThostFtdcQryBulletinField_NewsUrgency_set(swigCPtr, this, value);
  }

  public char getNewsUrgency() {
    return CTPMiniMdApiJNI.CThostFtdcQryBulletinField_NewsUrgency_get(swigCPtr, this);
  }

  public CThostFtdcQryBulletinField() {
    this(CTPMiniMdApiJNI.new_CThostFtdcQryBulletinField(), true);
  }

}
