/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcAccountregisterField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcAccountregisterField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcAccountregisterField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcAccountregisterField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcAccountregisterField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeDay(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_TradeDay_set(swigCPtr, this, value);
  }

  public String getTradeDay() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_TradeDay_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankBranchID_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankAccount_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_AccountID_get(swigCPtr, this);
  }

  public void setIdCardType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_IdCardType_set(swigCPtr, this, value);
  }

  public char getIdCardType() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_IdCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setCustomerName(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_CustomerName_set(swigCPtr, this, value);
  }

  public String getCustomerName() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_CustomerName_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_CurrencyID_get(swigCPtr, this);
  }

  public void setOpenOrDestroy(char value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_OpenOrDestroy_set(swigCPtr, this, value);
  }

  public char getOpenOrDestroy() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_OpenOrDestroy_get(swigCPtr, this);
  }

  public void setRegDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_RegDate_set(swigCPtr, this, value);
  }

  public String getRegDate() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_RegDate_get(swigCPtr, this);
  }

  public void setOutDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_OutDate_set(swigCPtr, this, value);
  }

  public String getOutDate() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_OutDate_get(swigCPtr, this);
  }

  public void setTID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_TID_get(swigCPtr, this);
  }

  public void setCustType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_CustType_set(swigCPtr, this, value);
  }

  public char getCustType() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_CustType_get(swigCPtr, this);
  }

  public void setBankAccType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankAccType_set(swigCPtr, this, value);
  }

  public char getBankAccType() {
    return CTPMiniTraderApiJNI.CThostFtdcAccountregisterField_BankAccType_get(swigCPtr, this);
  }

  public CThostFtdcAccountregisterField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcAccountregisterField(), true);
  }

}
