/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcUpdRiskForbiddenRightField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcUpdRiskForbiddenRightField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcUpdRiskForbiddenRightField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcUpdRiskForbiddenRightField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcUpdRiskForbiddenRightField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_InstrumentID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_UserID_get(swigCPtr, this);
  }

  public void setEventType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_EventType_set(swigCPtr, this, value);
  }

  public char getEventType() {
    return CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_EventType_get(swigCPtr, this);
  }

  public void setTradingRight(char value) {
    CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_TradingRight_set(swigCPtr, this, value);
  }

  public char getTradingRight() {
    return CTPMiniTraderApiJNI.CThostFtdcUpdRiskForbiddenRightField_TradingRight_get(swigCPtr, this);
  }

  public CThostFtdcUpdRiskForbiddenRightField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcUpdRiskForbiddenRightField(), true);
  }

}
