/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcQryIPUserACLField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQryIPUserACLField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQryIPUserACLField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcQryIPUserACLField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcQryIPUserACLField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(char value) {
    CTPMiniTraderApiJNI.CThostFtdcQryIPUserACLField_Mode_set(swigCPtr, this, value);
  }

  public char getMode() {
    return CTPMiniTraderApiJNI.CThostFtdcQryIPUserACLField_Mode_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcQryIPUserACLField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcQryIPUserACLField_IPAddress_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcQryIPUserACLField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcQryIPUserACLField_UserID_get(swigCPtr, this);
  }

  public CThostFtdcQryIPUserACLField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcQryIPUserACLField(), true);
  }

}
