/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcOptionSelfCloseField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcOptionSelfCloseField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcOptionSelfCloseField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcOptionSelfCloseField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcOptionSelfCloseField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InstrumentID_get(swigCPtr, this);
  }

  public void setOptionSelfCloseRef(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptionSelfCloseRef_set(swigCPtr, this, value);
  }

  public String getOptionSelfCloseRef() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptionSelfCloseRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_UserID_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_Volume_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_RequestID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BusinessUnit_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_HedgeFlag_get(swigCPtr, this);
  }

  public void setOptSelfCloseFlag(char value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptSelfCloseFlag_set(swigCPtr, this, value);
  }

  public char getOptSelfCloseFlag() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptSelfCloseFlag_get(swigCPtr, this);
  }

  public void setOptionSelfCloseLocalID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptionSelfCloseLocalID_set(swigCPtr, this, value);
  }

  public String getOptionSelfCloseLocalID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptionSelfCloseLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InstallID_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_NotifySequence_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_SettlementID_get(swigCPtr, this);
  }

  public void setOptionSelfCloseSysID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptionSelfCloseSysID_set(swigCPtr, this, value);
  }

  public String getOptionSelfCloseSysID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_OptionSelfCloseSysID_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InsertTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_CancelTime_get(swigCPtr, this);
  }

  public void setExecResult(char value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ExecResult_set(swigCPtr, this, value);
  }

  public char getExecResult() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ExecResult_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_SequenceNo_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_SessionID_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_UserProductInfo_get(swigCPtr, this);
  }

  public void setStatusMsg(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_StatusMsg_set(swigCPtr, this, value);
  }

  public String getStatusMsg() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_StatusMsg_get(swigCPtr, this);
  }

  public void setActiveUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ActiveUserID_set(swigCPtr, this, value);
  }

  public String getActiveUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_ActiveUserID_get(swigCPtr, this);
  }

  public void setBrokerOptionSelfCloseSeq(int value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BrokerOptionSelfCloseSeq_set(swigCPtr, this, value);
  }

  public int getBrokerOptionSelfCloseSeq() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BrokerOptionSelfCloseSeq_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_BranchID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_InvestUnitID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_AccountID_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_CurrencyID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcOptionSelfCloseField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcOptionSelfCloseField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcOptionSelfCloseField(), true);
  }

}
