/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcInputCombActionField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcInputCombActionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcInputCombActionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcInputCombActionField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcInputCombActionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_InstrumentID_get(swigCPtr, this);
  }

  public void setCombActionRef(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_CombActionRef_set(swigCPtr, this, value);
  }

  public String getCombActionRef() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_CombActionRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_UserID_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_Direction_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_Volume_get(swigCPtr, this);
  }

  public void setCombDirection(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_CombDirection_set(swigCPtr, this, value);
  }

  public char getCombDirection() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_CombDirection_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_HedgeFlag_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_BusinessUnit_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_ExchangeID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_MacAddress_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_InvestUnitID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return CTPMiniTraderApiJNI.CThostFtdcInputCombActionField_SessionID_get(swigCPtr, this);
  }

  public CThostFtdcInputCombActionField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcInputCombActionField(), true);
  }

}
