/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcTraderApi {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcTraderApi(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcTraderApi obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcTraderApi obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public static CThostFtdcTraderApi CreateFtdcTraderApi(String pszFlowPath) {
    long cPtr = CTPMiniTraderApiJNI.CThostFtdcTraderApi_CreateFtdcTraderApi__SWIG_0(pszFlowPath);
    return (cPtr == 0) ? null : new CThostFtdcTraderApi(cPtr, false);
  }

  public static CThostFtdcTraderApi CreateFtdcTraderApi() {
    long cPtr = CTPMiniTraderApiJNI.CThostFtdcTraderApi_CreateFtdcTraderApi__SWIG_1();
    return (cPtr == 0) ? null : new CThostFtdcTraderApi(cPtr, false);
  }

  public static String GetApiVersion() {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_GetApiVersion();
}

  public void Release() {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_Release(swigCPtr, this);
  }

  public void Init(boolean bContinuous) {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_Init__SWIG_0(swigCPtr, this, bContinuous);
  }

  public void Init() {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_Init__SWIG_1(swigCPtr, this);
  }

  public int Join() {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_Join(swigCPtr, this);
  }

  public String GetTradingDay() {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_GetTradingDay(swigCPtr, this);
}

  public void RegisterFront(String pszFrontAddress) {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_RegisterFront(swigCPtr, this, pszFrontAddress);
  }

  public void RegisterSpi(CThostFtdcTraderSpi pSpi) {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_RegisterSpi(swigCPtr, this, CThostFtdcTraderSpi.getCPtr(pSpi), pSpi);
  }

  public void SubscribePrivateTopic(THOST_TE_RESUME_TYPE nResumeType) {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_SubscribePrivateTopic(swigCPtr, this, nResumeType.swigValue());
  }

  public void SubscribePublicTopic(THOST_TE_RESUME_TYPE nResumeType) {
    CTPMiniTraderApiJNI.CThostFtdcTraderApi_SubscribePublicTopic(swigCPtr, this, nResumeType.swigValue());
  }

  public int SubscribeFlowCtrlWarning(String[] ppTraderID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_SubscribeFlowCtrlWarning(swigCPtr, this, ppTraderID);
  }

  public int UnSubscribeFlowCtrlWarning(String[] ppTraderID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_UnSubscribeFlowCtrlWarning(swigCPtr, this, ppTraderID);
  }

  public int ReqAuthenticate(CThostFtdcReqAuthenticateField pReqAuthenticateField, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqAuthenticate(swigCPtr, this, CThostFtdcReqAuthenticateField.getCPtr(pReqAuthenticateField), pReqAuthenticateField, nRequestID);
  }

  public int ReqUserLogin(CThostFtdcReqUserLoginField pReqUserLoginField, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqUserLogin(swigCPtr, this, CThostFtdcReqUserLoginField.getCPtr(pReqUserLoginField), pReqUserLoginField, nRequestID);
  }

  public int ReqUserLoginEncrypt(CThostFtdcReqUserLoginField pReqUserLoginField, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqUserLoginEncrypt(swigCPtr, this, CThostFtdcReqUserLoginField.getCPtr(pReqUserLoginField), pReqUserLoginField, nRequestID);
  }

  public int ReqUserLogout(CThostFtdcUserLogoutField pUserLogout, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqUserLogout(swigCPtr, this, CThostFtdcUserLogoutField.getCPtr(pUserLogout), pUserLogout, nRequestID);
  }

  public int ReqOrderInsert(CThostFtdcInputOrderField pInputOrder, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqOrderInsert(swigCPtr, this, CThostFtdcInputOrderField.getCPtr(pInputOrder), pInputOrder, nRequestID);
  }

  public int ReqOrderAction(CThostFtdcInputOrderActionField pInputOrderAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqOrderAction(swigCPtr, this, CThostFtdcInputOrderActionField.getCPtr(pInputOrderAction), pInputOrderAction, nRequestID);
  }

  public int ReqMKBatchOrderAction(CThostFtdcMKInputOrderActionField pMKInputOrderAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqMKBatchOrderAction(swigCPtr, this, CThostFtdcMKInputOrderActionField.getCPtr(pMKInputOrderAction), pMKInputOrderAction, nRequestID);
  }

  public int ReqExecOrderInsert(CThostFtdcInputExecOrderField pInputExecOrder, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqExecOrderInsert(swigCPtr, this, CThostFtdcInputExecOrderField.getCPtr(pInputExecOrder), pInputExecOrder, nRequestID);
  }

  public int ReqExecOrderAction(CThostFtdcInputExecOrderActionField pInputExecOrderAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqExecOrderAction(swigCPtr, this, CThostFtdcInputExecOrderActionField.getCPtr(pInputExecOrderAction), pInputExecOrderAction, nRequestID);
  }

  public int ReqForQuoteInsert(CThostFtdcInputForQuoteField pInputForQuote, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqForQuoteInsert(swigCPtr, this, CThostFtdcInputForQuoteField.getCPtr(pInputForQuote), pInputForQuote, nRequestID);
  }

  public int ReqQuoteInsert(CThostFtdcInputQuoteField pInputQuote, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQuoteInsert(swigCPtr, this, CThostFtdcInputQuoteField.getCPtr(pInputQuote), pInputQuote, nRequestID);
  }

  public int ReqQuoteAction(CThostFtdcInputQuoteActionField pInputQuoteAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQuoteAction(swigCPtr, this, CThostFtdcInputQuoteActionField.getCPtr(pInputQuoteAction), pInputQuoteAction, nRequestID);
  }

  public int ReqBatchOrderAction(CThostFtdcInputBatchOrderActionField pInputBatchOrderAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqBatchOrderAction(swigCPtr, this, CThostFtdcInputBatchOrderActionField.getCPtr(pInputBatchOrderAction), pInputBatchOrderAction, nRequestID);
  }

  public int ReqOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField pInputOptionSelfClose, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqOptionSelfCloseInsert(swigCPtr, this, CThostFtdcInputOptionSelfCloseField.getCPtr(pInputOptionSelfClose), pInputOptionSelfClose, nRequestID);
  }

  public int ReqOptionSelfCloseAction(CThostFtdcInputOptionSelfCloseActionField pInputOptionSelfCloseAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqOptionSelfCloseAction(swigCPtr, this, CThostFtdcInputOptionSelfCloseActionField.getCPtr(pInputOptionSelfCloseAction), pInputOptionSelfCloseAction, nRequestID);
  }

  public int ReqCombActionInsert(CThostFtdcInputCombActionField pInputCombAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqCombActionInsert(swigCPtr, this, CThostFtdcInputCombActionField.getCPtr(pInputCombAction), pInputCombAction, nRequestID);
  }

  public int ReqSubscribeFundChange(int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqSubscribeFundChange(swigCPtr, this, nRequestID);
  }

  public int ReqUnSubscribeFundChange(int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqUnSubscribeFundChange(swigCPtr, this, nRequestID);
  }

  public int ReqOffsetSetting(CThostFtdcInputOffsetSettingField pInputOffsetSetting, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqOffsetSetting(swigCPtr, this, CThostFtdcInputOffsetSettingField.getCPtr(pInputOffsetSetting), pInputOffsetSetting, nRequestID);
  }

  public int ReqCancelOffsetSetting(CThostFtdcInputOffsetSettingField pInputOffsetSetting, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqCancelOffsetSetting(swigCPtr, this, CThostFtdcInputOffsetSettingField.getCPtr(pInputOffsetSetting), pInputOffsetSetting, nRequestID);
  }

  public int ReqQryOrder(CThostFtdcQryOrderField pQryOrder, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryOrder(swigCPtr, this, CThostFtdcQryOrderField.getCPtr(pQryOrder), pQryOrder, nRequestID);
  }

  public int ReqQryTrade(CThostFtdcQryTradeField pQryTrade, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryTrade(swigCPtr, this, CThostFtdcQryTradeField.getCPtr(pQryTrade), pQryTrade, nRequestID);
  }

  public int ReqQryInvestorPosition(CThostFtdcQryInvestorPositionField pQryInvestorPosition, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInvestorPosition(swigCPtr, this, CThostFtdcQryInvestorPositionField.getCPtr(pQryInvestorPosition), pQryInvestorPosition, nRequestID);
  }

  public int ReqQryTradingAccount(CThostFtdcQryTradingAccountField pQryTradingAccount, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryTradingAccount(swigCPtr, this, CThostFtdcQryTradingAccountField.getCPtr(pQryTradingAccount), pQryTradingAccount, nRequestID);
  }

  public int ReqQryInvestor(CThostFtdcQryInvestorField pQryInvestor, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInvestor(swigCPtr, this, CThostFtdcQryInvestorField.getCPtr(pQryInvestor), pQryInvestor, nRequestID);
  }

  public int ReqQryTradingCode(CThostFtdcQryTradingCodeField pQryTradingCode, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryTradingCode(swigCPtr, this, CThostFtdcQryTradingCodeField.getCPtr(pQryTradingCode), pQryTradingCode, nRequestID);
  }

  public int ReqQryInstrumentMarginRate(CThostFtdcQryInstrumentMarginRateField pQryInstrumentMarginRate, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInstrumentMarginRate(swigCPtr, this, CThostFtdcQryInstrumentMarginRateField.getCPtr(pQryInstrumentMarginRate), pQryInstrumentMarginRate, nRequestID);
  }

  public int ReqQryInstrumentCommissionRate(CThostFtdcQryInstrumentCommissionRateField pQryInstrumentCommissionRate, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInstrumentCommissionRate(swigCPtr, this, CThostFtdcQryInstrumentCommissionRateField.getCPtr(pQryInstrumentCommissionRate), pQryInstrumentCommissionRate, nRequestID);
  }

  public int ReqQryExchange(CThostFtdcQryExchangeField pQryExchange, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryExchange(swigCPtr, this, CThostFtdcQryExchangeField.getCPtr(pQryExchange), pQryExchange, nRequestID);
  }

  public int ReqQryProduct(CThostFtdcQryProductField pQryProduct, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryProduct(swigCPtr, this, CThostFtdcQryProductField.getCPtr(pQryProduct), pQryProduct, nRequestID);
  }

  public int ReqQryInstrument(CThostFtdcQryInstrumentField pQryInstrument, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInstrument(swigCPtr, this, CThostFtdcQryInstrumentField.getCPtr(pQryInstrument), pQryInstrument, nRequestID);
  }

  public int ReqQryCombInstrument(CThostFtdcQryCombInstrumentField pQryCombInstrument, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryCombInstrument(swigCPtr, this, CThostFtdcQryCombInstrumentField.getCPtr(pQryCombInstrument), pQryCombInstrument, nRequestID);
  }

  public int ReqQryRCAMSInvestorProdMargin(CThostFtdcQryRCAMSInvestorProdMarginField pQryRCAMSInvestorProdMargin, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryRCAMSInvestorProdMargin(swigCPtr, this, CThostFtdcQryRCAMSInvestorProdMarginField.getCPtr(pQryRCAMSInvestorProdMargin), pQryRCAMSInvestorProdMargin, nRequestID);
  }

  public int ReqQryRCAMSInvestorCombPosition(CThostFtdcQryRCAMSInvestorCombPositionField pQryRCAMSInvestorCombPosition, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryRCAMSInvestorCombPosition(swigCPtr, this, CThostFtdcQryRCAMSInvestorCombPositionField.getCPtr(pQryRCAMSInvestorCombPosition), pQryRCAMSInvestorCombPosition, nRequestID);
  }

  public int ReqQryInvestorPositionForComb(CThostFtdcQryInvestorPositionForCombField pQryIPForComb, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInvestorPositionForComb(swigCPtr, this, CThostFtdcQryInvestorPositionForCombField.getCPtr(pQryIPForComb), pQryIPForComb, nRequestID);
  }

  public int ReqQryCombAction(CThostFtdcQryCombActionField pQryCombAction, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryCombAction(swigCPtr, this, CThostFtdcQryCombActionField.getCPtr(pQryCombAction), pQryCombAction, nRequestID);
  }

  public int ReqQryDepthMarketData(CThostFtdcQryDepthMarketDataField pQryDepthMarketData, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryDepthMarketData(swigCPtr, this, CThostFtdcQryDepthMarketDataField.getCPtr(pQryDepthMarketData), pQryDepthMarketData, nRequestID);
  }

  public int ReqQryOptionSelfClose(CThostFtdcQryOptionSelfCloseField pQryOptionSelfClose, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryOptionSelfClose(swigCPtr, this, CThostFtdcQryOptionSelfCloseField.getCPtr(pQryOptionSelfClose), pQryOptionSelfClose, nRequestID);
  }

  public int ReqQryInstrumentStatus(CThostFtdcQryInstrumentStatusField pQryInstrumentStatus, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInstrumentStatus(swigCPtr, this, CThostFtdcQryInstrumentStatusField.getCPtr(pQryInstrumentStatus), pQryInstrumentStatus, nRequestID);
  }

  public int ReqQryInvestorPositionDetail(CThostFtdcQryInvestorPositionDetailField pQryInvestorPositionDetail, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInvestorPositionDetail(swigCPtr, this, CThostFtdcQryInvestorPositionDetailField.getCPtr(pQryInvestorPositionDetail), pQryInvestorPositionDetail, nRequestID);
  }

  public int ReqQryExchangeMarginRate(CThostFtdcQryExchangeMarginRateField pQryExchangeMarginRate, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryExchangeMarginRate(swigCPtr, this, CThostFtdcQryExchangeMarginRateField.getCPtr(pQryExchangeMarginRate), pQryExchangeMarginRate, nRequestID);
  }

  public int ReqQryExchangeMarginRateAdjust(CThostFtdcQryExchangeMarginRateAdjustField pQryExchangeMarginRateAdjust, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryExchangeMarginRateAdjust(swigCPtr, this, CThostFtdcQryExchangeMarginRateAdjustField.getCPtr(pQryExchangeMarginRateAdjust), pQryExchangeMarginRateAdjust, nRequestID);
  }

  public int ReqQryOptionInstrTradeCost(CThostFtdcQryOptionInstrTradeCostField pQryOptionInstrTradeCost, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryOptionInstrTradeCost(swigCPtr, this, CThostFtdcQryOptionInstrTradeCostField.getCPtr(pQryOptionInstrTradeCost), pQryOptionInstrTradeCost, nRequestID);
  }

  public int ReqQryOptionInstrCommRate(CThostFtdcQryOptionInstrCommRateField pQryOptionInstrCommRate, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryOptionInstrCommRate(swigCPtr, this, CThostFtdcQryOptionInstrCommRateField.getCPtr(pQryOptionInstrCommRate), pQryOptionInstrCommRate, nRequestID);
  }

  public int ReqQryExecOrder(CThostFtdcQryExecOrderField pQryExecOrder, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryExecOrder(swigCPtr, this, CThostFtdcQryExecOrderField.getCPtr(pQryExecOrder), pQryExecOrder, nRequestID);
  }

  public int ReqQryForQuote(CThostFtdcQryForQuoteField pQryForQuote, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryForQuote(swigCPtr, this, CThostFtdcQryForQuoteField.getCPtr(pQryForQuote), pQryForQuote, nRequestID);
  }

  public int ReqQryQuote(CThostFtdcQryQuoteField pQryQuote, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryQuote(swigCPtr, this, CThostFtdcQryQuoteField.getCPtr(pQryQuote), pQryQuote, nRequestID);
  }

  public int ReqQryInstrumentOrderCommRate(CThostFtdcQryInstrumentOrderCommRateField pQryInstrumentOrderCommRate, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInstrumentOrderCommRate(swigCPtr, this, CThostFtdcQryInstrumentOrderCommRateField.getCPtr(pQryInstrumentOrderCommRate), pQryInstrumentOrderCommRate, nRequestID);
  }

  public int ReqQryForQuoteParam(CThostFtdcQryForQuoteParamField pQryForQuoteParam, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryForQuoteParam(swigCPtr, this, CThostFtdcQryForQuoteParamField.getCPtr(pQryForQuoteParam), pQryForQuoteParam, nRequestID);
  }

  public int ReqQryTraderOffer(CThostFtdcQryTraderOfferField pQryTraderOffer, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryTraderOffer(swigCPtr, this, CThostFtdcQryTraderOfferField.getCPtr(pQryTraderOffer), pQryTraderOffer, nRequestID);
  }

  public int ReqQryInvestorProdSPBMDetail(CThostFtdcQryInvestorProdSPBMDetailField pQryInvestorProdSPBMDetail, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryInvestorProdSPBMDetail(swigCPtr, this, CThostFtdcQryInvestorProdSPBMDetailField.getCPtr(pQryInvestorProdSPBMDetail), pQryInvestorProdSPBMDetail, nRequestID);
  }

  public int ReqQrySPMMInvestorCommodityGroupMargin(CThostFtdcQrySPMMInvestorCommodityGroupMarginField pQrySPMMInvestorCommodityGroupMargin, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQrySPMMInvestorCommodityGroupMargin(swigCPtr, this, CThostFtdcQrySPMMInvestorCommodityGroupMarginField.getCPtr(pQrySPMMInvestorCommodityGroupMargin), pQrySPMMInvestorCommodityGroupMargin, nRequestID);
  }

  public int ReqQryRULEInvestorProdMargin(CThostFtdcQryRULEInvestorProdMarginField pQryRULEInvestorProdMargin, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryRULEInvestorProdMargin(swigCPtr, this, CThostFtdcQryRULEInvestorProdMarginField.getCPtr(pQryRULEInvestorProdMargin), pQryRULEInvestorProdMargin, nRequestID);
  }

  public int ReqQryControlParam(CThostFtdcQryControlParamField pQryControlParam, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryControlParam(swigCPtr, this, CThostFtdcQryControlParamField.getCPtr(pQryControlParam), pQryControlParam, nRequestID);
  }

  public int ReqQryOffsetSetting(CThostFtdcQryOffsetSettingField pQryOffsetSetting, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqQryOffsetSetting(swigCPtr, this, CThostFtdcQryOffsetSettingField.getCPtr(pQryOffsetSetting), pQryOffsetSetting, nRequestID);
  }

  public int ReqUserPasswordUpdate(CThostFtdcUserPasswordUpdateField pUserPasswordUpdate, int nRequestID) {
    return CTPMiniTraderApiJNI.CThostFtdcTraderApi_ReqUserPasswordUpdate(swigCPtr, this, CThostFtdcUserPasswordUpdateField.getCPtr(pUserPasswordUpdate), pUserPasswordUpdate, nRequestID);
  }

}
