/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcInvestorProductGroupMarginField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcInvestorProductGroupMarginField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcInvestorProductGroupMarginField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcInvestorProductGroupMarginField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcInvestorProductGroupMarginField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductGroupID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ProductGroupID_set(swigCPtr, this, value);
  }

  public String getProductGroupID() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ProductGroupID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_InvestorID_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_SettlementID_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_FrozenMargin_get(swigCPtr, this);
  }

  public void setLongFrozenMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongFrozenMargin_set(swigCPtr, this, value);
  }

  public double getLongFrozenMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongFrozenMargin_get(swigCPtr, this);
  }

  public void setShortFrozenMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortFrozenMargin_set(swigCPtr, this, value);
  }

  public double getShortFrozenMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortFrozenMargin_get(swigCPtr, this);
  }

  public void setUseMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_UseMargin_set(swigCPtr, this, value);
  }

  public double getUseMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_UseMargin_get(swigCPtr, this);
  }

  public void setLongUseMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongUseMargin_set(swigCPtr, this, value);
  }

  public double getLongUseMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongUseMargin_get(swigCPtr, this);
  }

  public void setShortUseMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortUseMargin_set(swigCPtr, this, value);
  }

  public double getShortUseMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortUseMargin_get(swigCPtr, this);
  }

  public void setExchMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ExchMargin_set(swigCPtr, this, value);
  }

  public double getExchMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ExchMargin_get(swigCPtr, this);
  }

  public void setLongExchMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongExchMargin_set(swigCPtr, this, value);
  }

  public double getLongExchMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongExchMargin_get(swigCPtr, this);
  }

  public void setShortExchMargin(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortExchMargin_set(swigCPtr, this, value);
  }

  public double getShortExchMargin() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortExchMargin_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_CloseProfit_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_Commission_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_FrozenCash_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_CashIn_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_PositionProfit_get(swigCPtr, this);
  }

  public void setOffsetAmount(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_OffsetAmount_set(swigCPtr, this, value);
  }

  public double getOffsetAmount() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_OffsetAmount_get(swigCPtr, this);
  }

  public void setLongOffsetAmount(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongOffsetAmount_set(swigCPtr, this, value);
  }

  public double getLongOffsetAmount() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongOffsetAmount_get(swigCPtr, this);
  }

  public void setShortOffsetAmount(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortOffsetAmount_set(swigCPtr, this, value);
  }

  public double getShortOffsetAmount() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortOffsetAmount_get(swigCPtr, this);
  }

  public void setExchOffsetAmount(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ExchOffsetAmount_set(swigCPtr, this, value);
  }

  public double getExchOffsetAmount() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ExchOffsetAmount_get(swigCPtr, this);
  }

  public void setLongExchOffsetAmount(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongExchOffsetAmount_set(swigCPtr, this, value);
  }

  public double getLongExchOffsetAmount() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_LongExchOffsetAmount_get(swigCPtr, this);
  }

  public void setShortExchOffsetAmount(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortExchOffsetAmount_set(swigCPtr, this, value);
  }

  public double getShortExchOffsetAmount() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_ShortExchOffsetAmount_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return CTPMiniTraderApiJNI.CThostFtdcInvestorProductGroupMarginField_HedgeFlag_get(swigCPtr, this);
  }

  public CThostFtdcInvestorProductGroupMarginField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcInvestorProductGroupMarginField(), true);
  }

}
