/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcRspFutureSignInField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcRspFutureSignInField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcRspFutureSignInField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcRspFutureSignInField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcRspFutureSignInField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeCode(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradeCode_set(swigCPtr, this, value);
  }

  public String getTradeCode() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradeCode_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BankBranchID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradeTime_get(swigCPtr, this);
  }

  public void setBankSerial(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BankSerial_set(swigCPtr, this, value);
  }

  public String getBankSerial() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BankSerial_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TradingDay_get(swigCPtr, this);
  }

  public void setPlateSerial(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_PlateSerial_set(swigCPtr, this, value);
  }

  public int getPlateSerial() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_PlateSerial_get(swigCPtr, this);
  }

  public void setLastFragment(char value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_LastFragment_set(swigCPtr, this, value);
  }

  public char getLastFragment() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_LastFragment_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_SessionID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_InstallID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_UserID_get(swigCPtr, this);
  }

  public void setDigest(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_Digest_set(swigCPtr, this, value);
  }

  public String getDigest() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_Digest_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_CurrencyID_get(swigCPtr, this);
  }

  public void setDeviceID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_DeviceID_set(swigCPtr, this, value);
  }

  public String getDeviceID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_DeviceID_get(swigCPtr, this);
  }

  public void setBrokerIDByBank(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BrokerIDByBank_set(swigCPtr, this, value);
  }

  public String getBrokerIDByBank() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_BrokerIDByBank_get(swigCPtr, this);
  }

  public void setOperNo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_OperNo_set(swigCPtr, this, value);
  }

  public String getOperNo() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_OperNo_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_RequestID_get(swigCPtr, this);
  }

  public void setTID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_TID_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_ErrorMsg_get(swigCPtr, this);
  }

  public void setPinKey(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_PinKey_set(swigCPtr, this, value);
  }

  public String getPinKey() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_PinKey_get(swigCPtr, this);
  }

  public void setMacKey(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_MacKey_set(swigCPtr, this, value);
  }

  public String getMacKey() {
    return CTPMiniTraderApiJNI.CThostFtdcRspFutureSignInField_MacKey_get(swigCPtr, this);
  }

  public CThostFtdcRspFutureSignInField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcRspFutureSignInField(), true);
  }

}
