/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcQryHedgeConfirmField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQryHedgeConfirmField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQryHedgeConfirmField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcQryHedgeConfirmField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcQryHedgeConfirmField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniTraderApiJNI.CThostFtdcQryHedgeConfirmField_ExchangeID_get(swigCPtr, this);
  }

  public CThostFtdcQryHedgeConfirmField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcQryHedgeConfirmField(), true);
  }

}
