/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcMarketDataStaticField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcMarketDataStaticField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcMarketDataStaticField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcMarketDataStaticField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcMarketDataStaticField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOpenPrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_OpenPrice_set(swigCPtr, this, value);
  }

  public double getOpenPrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_OpenPrice_get(swigCPtr, this);
  }

  public void setHighestPrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_HighestPrice_set(swigCPtr, this, value);
  }

  public double getHighestPrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_HighestPrice_get(swigCPtr, this);
  }

  public void setLowestPrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_LowestPrice_set(swigCPtr, this, value);
  }

  public double getLowestPrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_LowestPrice_get(swigCPtr, this);
  }

  public void setClosePrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_ClosePrice_set(swigCPtr, this, value);
  }

  public double getClosePrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_ClosePrice_get(swigCPtr, this);
  }

  public void setUpperLimitPrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_UpperLimitPrice_set(swigCPtr, this, value);
  }

  public double getUpperLimitPrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_UpperLimitPrice_get(swigCPtr, this);
  }

  public void setLowerLimitPrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_LowerLimitPrice_set(swigCPtr, this, value);
  }

  public double getLowerLimitPrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_LowerLimitPrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_SettlementPrice_get(swigCPtr, this);
  }

  public void setCurrDelta(double value) {
    CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_CurrDelta_set(swigCPtr, this, value);
  }

  public double getCurrDelta() {
    return CTPMiniTraderApiJNI.CThostFtdcMarketDataStaticField_CurrDelta_get(swigCPtr, this);
  }

  public CThostFtdcMarketDataStaticField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcMarketDataStaticField(), true);
  }

}
