/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcControlParamField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcControlParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcControlParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcControlParamField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcControlParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcControlParamField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcControlParamField_InvestorID_get(swigCPtr, this);
  }

  public void setControlParamID(char value) {
    CTPMiniTraderApiJNI.CThostFtdcControlParamField_ControlParamID_set(swigCPtr, this, value);
  }

  public char getControlParamID() {
    return CTPMiniTraderApiJNI.CThostFtdcControlParamField_ControlParamID_get(swigCPtr, this);
  }

  public void setControlParamValue(String value) {
    CTPMiniTraderApiJNI.CThostFtdcControlParamField_ControlParamValue_set(swigCPtr, this, value);
  }

  public String getControlParamValue() {
    return CTPMiniTraderApiJNI.CThostFtdcControlParamField_ControlParamValue_get(swigCPtr, this);
  }

  public void setMemo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcControlParamField_Memo_set(swigCPtr, this, value);
  }

  public String getMemo() {
    return CTPMiniTraderApiJNI.CThostFtdcControlParamField_Memo_get(swigCPtr, this);
  }

  public CThostFtdcControlParamField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcControlParamField(), true);
  }

}
