/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcRspSyncKeyField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcRspSyncKeyField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcRspSyncKeyField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcRspSyncKeyField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcRspSyncKeyField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeCode(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradeCode_set(swigCPtr, this, value);
  }

  public String getTradeCode() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradeCode_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BankBranchID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradeTime_get(swigCPtr, this);
  }

  public void setBankSerial(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BankSerial_set(swigCPtr, this, value);
  }

  public String getBankSerial() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BankSerial_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TradingDay_get(swigCPtr, this);
  }

  public void setPlateSerial(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_PlateSerial_set(swigCPtr, this, value);
  }

  public int getPlateSerial() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_PlateSerial_get(swigCPtr, this);
  }

  public void setLastFragment(char value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_LastFragment_set(swigCPtr, this, value);
  }

  public char getLastFragment() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_LastFragment_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_SessionID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_InstallID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_UserID_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_Message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_Message_get(swigCPtr, this);
  }

  public void setDeviceID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_DeviceID_set(swigCPtr, this, value);
  }

  public String getDeviceID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_DeviceID_get(swigCPtr, this);
  }

  public void setBrokerIDByBank(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BrokerIDByBank_set(swigCPtr, this, value);
  }

  public String getBrokerIDByBank() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_BrokerIDByBank_get(swigCPtr, this);
  }

  public void setOperNo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_OperNo_set(swigCPtr, this, value);
  }

  public String getOperNo() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_OperNo_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_RequestID_get(swigCPtr, this);
  }

  public void setTID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_TID_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return CTPMiniTraderApiJNI.CThostFtdcRspSyncKeyField_ErrorMsg_get(swigCPtr, this);
  }

  public CThostFtdcRspSyncKeyField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcRspSyncKeyField(), true);
  }

}
