/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcCancelOffsetSettingField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcCancelOffsetSettingField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcCancelOffsetSettingField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcCancelOffsetSettingField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcCancelOffsetSettingField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_InstrumentID_get(swigCPtr, this);
  }

  public void setUnderlyingInstrID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_UnderlyingInstrID_set(swigCPtr, this, value);
  }

  public String getUnderlyingInstrID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_UnderlyingInstrID_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ProductID_get(swigCPtr, this);
  }

  public void setOffsetType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_OffsetType_set(swigCPtr, this, value);
  }

  public char getOffsetType() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_OffsetType_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_Volume_get(swigCPtr, this);
  }

  public void setIsOffset(int value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_IsOffset_set(swigCPtr, this, value);
  }

  public int getIsOffset() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_IsOffset_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_RequestID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_UserID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_MacAddress_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setExchangeSerialNo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeSerialNo_set(swigCPtr, this, value);
  }

  public String getExchangeSerialNo() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeSerialNo_get(swigCPtr, this);
  }

  public void setExchangeProductID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeProductID_set(swigCPtr, this, value);
  }

  public String getExchangeProductID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ExchangeProductID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_InstallID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ClientID_get(swigCPtr, this);
  }

  public void setOrderActionStatus(char value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_OrderActionStatus_set(swigCPtr, this, value);
  }

  public char getOrderActionStatus() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_OrderActionStatus_get(swigCPtr, this);
  }

  public void setStatusMsg(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_StatusMsg_set(swigCPtr, this, value);
  }

  public String getStatusMsg() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_StatusMsg_get(swigCPtr, this);
  }

  public void setActionLocalID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ActionLocalID_set(swigCPtr, this, value);
  }

  public String getActionLocalID() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ActionLocalID_get(swigCPtr, this);
  }

  public void setActionDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ActionDate_set(swigCPtr, this, value);
  }

  public String getActionDate() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ActionDate_get(swigCPtr, this);
  }

  public void setActionTime(String value) {
    CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ActionTime_set(swigCPtr, this, value);
  }

  public String getActionTime() {
    return CTPMiniTraderApiJNI.CThostFtdcCancelOffsetSettingField_ActionTime_get(swigCPtr, this);
  }

  public CThostFtdcCancelOffsetSettingField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcCancelOffsetSettingField(), true);
  }

}
