/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcInstrumentField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcInstrumentField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcInstrumentField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcInstrumentField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcInstrumentField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ExchangeID_get(swigCPtr, this);
  }

  public void setInstrumentName(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_InstrumentName_set(swigCPtr, this, value);
  }

  public String getInstrumentName() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_InstrumentName_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ProductID_get(swigCPtr, this);
  }

  public void setProductClass(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ProductClass_set(swigCPtr, this, value);
  }

  public char getProductClass() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ProductClass_get(swigCPtr, this);
  }

  public void setDeliveryYear(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_DeliveryYear_set(swigCPtr, this, value);
  }

  public int getDeliveryYear() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_DeliveryYear_get(swigCPtr, this);
  }

  public void setDeliveryMonth(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_DeliveryMonth_set(swigCPtr, this, value);
  }

  public int getDeliveryMonth() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_DeliveryMonth_get(swigCPtr, this);
  }

  public void setMaxMarketOrderVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MaxMarketOrderVolume_set(swigCPtr, this, value);
  }

  public int getMaxMarketOrderVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MaxMarketOrderVolume_get(swigCPtr, this);
  }

  public void setMinMarketOrderVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MinMarketOrderVolume_set(swigCPtr, this, value);
  }

  public int getMinMarketOrderVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MinMarketOrderVolume_get(swigCPtr, this);
  }

  public void setMaxLimitOrderVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MaxLimitOrderVolume_set(swigCPtr, this, value);
  }

  public int getMaxLimitOrderVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MaxLimitOrderVolume_get(swigCPtr, this);
  }

  public void setMinLimitOrderVolume(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MinLimitOrderVolume_set(swigCPtr, this, value);
  }

  public int getMinLimitOrderVolume() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MinLimitOrderVolume_get(swigCPtr, this);
  }

  public void setVolumeMultiple(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_VolumeMultiple_set(swigCPtr, this, value);
  }

  public int getVolumeMultiple() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_VolumeMultiple_get(swigCPtr, this);
  }

  public void setPriceTick(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_PriceTick_set(swigCPtr, this, value);
  }

  public double getPriceTick() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_PriceTick_get(swigCPtr, this);
  }

  public void setCreateDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_CreateDate_set(swigCPtr, this, value);
  }

  public String getCreateDate() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_CreateDate_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_OpenDate_get(swigCPtr, this);
  }

  public void setExpireDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ExpireDate_set(swigCPtr, this, value);
  }

  public String getExpireDate() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ExpireDate_get(swigCPtr, this);
  }

  public void setStartDelivDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_StartDelivDate_set(swigCPtr, this, value);
  }

  public String getStartDelivDate() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_StartDelivDate_get(swigCPtr, this);
  }

  public void setEndDelivDate(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_EndDelivDate_set(swigCPtr, this, value);
  }

  public String getEndDelivDate() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_EndDelivDate_get(swigCPtr, this);
  }

  public void setInstLifePhase(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_InstLifePhase_set(swigCPtr, this, value);
  }

  public char getInstLifePhase() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_InstLifePhase_get(swigCPtr, this);
  }

  public void setIsTrading(int value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_IsTrading_set(swigCPtr, this, value);
  }

  public int getIsTrading() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_IsTrading_get(swigCPtr, this);
  }

  public void setPositionType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_PositionType_set(swigCPtr, this, value);
  }

  public char getPositionType() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_PositionType_get(swigCPtr, this);
  }

  public void setPositionDateType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_PositionDateType_set(swigCPtr, this, value);
  }

  public char getPositionDateType() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_PositionDateType_get(swigCPtr, this);
  }

  public void setLongMarginRatio(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_LongMarginRatio_set(swigCPtr, this, value);
  }

  public double getLongMarginRatio() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_LongMarginRatio_get(swigCPtr, this);
  }

  public void setShortMarginRatio(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ShortMarginRatio_set(swigCPtr, this, value);
  }

  public double getShortMarginRatio() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_ShortMarginRatio_get(swigCPtr, this);
  }

  public void setMaxMarginSideAlgorithm(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MaxMarginSideAlgorithm_set(swigCPtr, this, value);
  }

  public char getMaxMarginSideAlgorithm() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_MaxMarginSideAlgorithm_get(swigCPtr, this);
  }

  public void setUnderlyingInstrID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_UnderlyingInstrID_set(swigCPtr, this, value);
  }

  public String getUnderlyingInstrID() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_UnderlyingInstrID_get(swigCPtr, this);
  }

  public void setStrikePrice(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_StrikePrice_set(swigCPtr, this, value);
  }

  public double getStrikePrice() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_StrikePrice_get(swigCPtr, this);
  }

  public void setOptionsType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_OptionsType_set(swigCPtr, this, value);
  }

  public char getOptionsType() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_OptionsType_get(swigCPtr, this);
  }

  public void setUnderlyingMultiple(double value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_UnderlyingMultiple_set(swigCPtr, this, value);
  }

  public double getUnderlyingMultiple() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_UnderlyingMultiple_get(swigCPtr, this);
  }

  public void setCombinationType(char value) {
    CTPMiniTraderApiJNI.CThostFtdcInstrumentField_CombinationType_set(swigCPtr, this, value);
  }

  public char getCombinationType() {
    return CTPMiniTraderApiJNI.CThostFtdcInstrumentField_CombinationType_get(swigCPtr, this);
  }

  public CThostFtdcInstrumentField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcInstrumentField(), true);
  }

}
