/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctpmini.tradeapi;

public class CThostFtdcUserSystemInfoField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcUserSystemInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcUserSystemInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcUserSystemInfoField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTPMiniTraderApiJNI.delete_CThostFtdcUserSystemInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_UserID_get(swigCPtr, this);
  }

  public void setClientSystemInfoLen(int value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfoLen_set(swigCPtr, this, value);
  }

  public int getClientSystemInfoLen() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfoLen_get(swigCPtr, this);
  }

  public void setClientSystemInfo(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfo_set(swigCPtr, this, value);
  }

  public String getClientSystemInfo() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfo_get(swigCPtr, this);
  }

  public void setClientPublicIP(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientPublicIP_set(swigCPtr, this, value);
  }

  public String getClientPublicIP() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientPublicIP_get(swigCPtr, this);
  }

  public void setClientIPPort(int value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientIPPort_set(swigCPtr, this, value);
  }

  public int getClientIPPort() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientIPPort_get(swigCPtr, this);
  }

  public void setClientLoginTime(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientLoginTime_set(swigCPtr, this, value);
  }

  public String getClientLoginTime() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientLoginTime_get(swigCPtr, this);
  }

  public void setClientAppID(String value) {
    CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientAppID_set(swigCPtr, this, value);
  }

  public String getClientAppID() {
    return CTPMiniTraderApiJNI.CThostFtdcUserSystemInfoField_ClientAppID_get(swigCPtr, this);
  }

  public CThostFtdcUserSystemInfoField() {
    this(CTPMiniTraderApiJNI.new_CThostFtdcUserSystemInfoField(), true);
  }

}
